### PR TITLE
update version 0.8.0

### PR DESCRIPTION
**Pull request by aloctavodia**
Update examples to Bambi version 0.8.0
add random_seed to `fit()` method

### CODE REVIEW

**Comment by tomicapretto** [comment]
@aloctavodia could you try to remove the environment, then create again from the environment.yml and trying to reproduce the results? I couldn't create an environment from the previous file (dependency issues). The following are the changes I introduced:

* Updated environment.yml
* Set number of chains to 4 (so it does not depend on where you run it)
* Create `SEED` variable.
* Run all again.

**Comment by canyon289** [comment]
Environment creation works for me on Linux

image

**Comment by tomicapretto** [comment]
> Environment creation works for me on Linux
> 
> image

Awesome! Thanks for checking!

**Comment by aloctavodia** [comment]
Is this ready to merge?

**Comment by tomicapretto** [comment]
@aloctavodia if you can check the environment file is working on your side, yes, it is ready to merge.

**Comment by aloctavodia** [comment]
I can install it, but the `notebook` package is missing from the environment and more important theano is giving trouble, models do not even run. Trying to figure out what is going on. 

Update:
I keep getting the same errors
1) WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions. 

2) Exception: ("Compilation failed (return status=1): as: unrecognized option '--gdwarf-5'. ", 'FunctionGraph(Elemwise{true_div,no_inplace}(TensorConstant{1.0}, TensorConstant{0.00222630..4298923615}))')

I tried different combinations of packages and still get the same errors (or conflicts between packages)

**Comment by aloctavodia** [comment]
@canyon289 are you able to run bambi with this environment?

**Comment by tomicapretto** [comment]
@aloctavodia I am using Jupyter from within Visual Studio Code. I'll try with plain Jupyter (there I'll notice jupyter is missing)

**Comment by aloctavodia** [comment]
I am also using Jupyter from within Visual Studio Code.

**Comment by canyon289** [comment]
It works for me once I added jupyterlab to the environment on linux

**Comment by aloctavodia** [comment]
In that case I will merge this and later find out what is going on with my conda. Could you please send me a screencapture to replace figure 2. And also the updated table 1.

**Comment by tomicapretto** [comment]
@aloctavodia sorry for the delay. I couldn't work on this yet. I'll rebuild everything from scratch to double-check everything is fine.

I'll also send captures ASAP

**Comment by aloctavodia** [comment]
Thanks I tried so many combinations that I don't know what else to do :-(

**Pull request merged**
